version: "3.8"
services:
  db:
    image: mysql
    volumes:
      - ./volumes/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
    expose:
      - "3306"
